# Ctrl-A mode
set -g prefix C-a
unbind-key C-b
bind-key C-a send-prefix

# mouse on
set -g mouse on

## Vi mode-keys
set-window-option -g mode-keys vi

# Vim v and y keys
bind-key -T copy-mode-vi 'v' send -X begin-selection
bind-key -T copy-mode-vi 'y' send -X copy-selection-and-cancel

# ctrl-a ctrl-a
unbind l
unbind-key l
bind C-a last-window
bind-key C-a last-window

# Experimental

# History limit
set-option -g history-limit 9999

# start window index at 1
set -g base-index 1

# start pane index at 1
setw -g pane-base-index 1

# highlight window when it has new activity
setw -g monitor-activity on
set -g visual-activity on

# re-number windows when one is closed
set -g renumber-windows on


############################
## Status Bar
############################
#
## set refresh interval for status bar
#set -g status-interval 30
#
## center the status bar
#set -g status-justify left
#
## show session, window, pane in left status bar
#set -g status-left-length 40
#set -g status-left '#[fg=green]#S#[fg=white] #I:#P #[default]'
#
## show hostname, date, time, and battery in right status bar
#set-option -g status-right '#($HOME/bin/battery.sh)#[default] \
##[fg=colour208]#($HOME/bin/osx-cpu-temp/osx-cpu-temp)#[default] | %d/%m/%y %I:%M#[default]'
# set -g status-right "Hola!"

# set syncro
bind-key S set-window-option synchronize-panes\; display-message "synchronize-panes is now #{?pane_synchronized,on,off}"

# split panes using | and -
bind | split-window -h
bind - split-window -v
unbind '"'
unbind %

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'jimeh/tmux-themepack'
set -g @themepack 'powerline/block/cyan'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run -b '~/.tmux/plugins/tpm/tpm'
